# Generated by Django 5.1.3 on 2024-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gullar',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
